/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUploadRouteImport } from './routes/_authenticated/upload'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPremiumRouteImport } from './routes/_authenticated/premium'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedMyUploadsRouteImport } from './routes/_authenticated/my-uploads'
import { Route as AuthenticatedLibraryRouteImport } from './routes/_authenticated/library'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedBookmarksRouteImport } from './routes/_authenticated/bookmarks'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedPreviewResourceIdRouteImport } from './routes/_authenticated/preview.$resourceId'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminCategoriesRouteImport } from './routes/_authenticated/admin.categories'
import { Route as AuthenticatedAdminApprovalsRouteImport } from './routes/_authenticated/admin.approvals'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUploadRoute = AuthenticatedUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPremiumRoute = AuthenticatedPremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMyUploadsRoute = AuthenticatedMyUploadsRouteImport.update({
  id: '/my-uploads',
  path: '/my-uploads',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLibraryRoute = AuthenticatedLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBookmarksRoute = AuthenticatedBookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedPreviewResourceIdRoute =
  AuthenticatedPreviewResourceIdRouteImport.update({
    id: '/preview/$resourceId',
    path: '/preview/$resourceId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminCategoriesRoute =
  AuthenticatedAdminCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminApprovalsRoute =
  AuthenticatedAdminApprovalsRouteImport.update({
    id: '/approvals',
    path: '/approvals',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/bookmarks': typeof AuthenticatedBookmarksRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/my-uploads': typeof AuthenticatedMyUploadsRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/premium': typeof AuthenticatedPremiumRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/upload': typeof AuthenticatedUploadRoute
  '/admin/approvals': typeof AuthenticatedAdminApprovalsRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/preview/$resourceId': typeof AuthenticatedPreviewResourceIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/bookmarks': typeof AuthenticatedBookmarksRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/my-uploads': typeof AuthenticatedMyUploadsRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/premium': typeof AuthenticatedPremiumRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/upload': typeof AuthenticatedUploadRoute
  '/admin/approvals': typeof AuthenticatedAdminApprovalsRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/preview/$resourceId': typeof AuthenticatedPreviewResourceIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/bookmarks': typeof AuthenticatedBookmarksRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/library': typeof AuthenticatedLibraryRoute
  '/_authenticated/my-uploads': typeof AuthenticatedMyUploadsRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/premium': typeof AuthenticatedPremiumRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/upload': typeof AuthenticatedUploadRoute
  '/_authenticated/admin/approvals': typeof AuthenticatedAdminApprovalsRoute
  '/_authenticated/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/preview/$resourceId': typeof AuthenticatedPreviewResourceIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/pricing'
    | '/reset-password'
    | '/verify-email'
    | '/admin'
    | '/bookmarks'
    | '/dashboard'
    | '/library'
    | '/my-uploads'
    | '/notifications'
    | '/premium'
    | '/profile'
    | '/settings'
    | '/upload'
    | '/admin/approvals'
    | '/admin/categories'
    | '/admin/users'
    | '/preview/$resourceId'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/pricing'
    | '/reset-password'
    | '/verify-email'
    | '/bookmarks'
    | '/dashboard'
    | '/library'
    | '/my-uploads'
    | '/notifications'
    | '/premium'
    | '/profile'
    | '/settings'
    | '/upload'
    | '/admin/approvals'
    | '/admin/categories'
    | '/admin/users'
    | '/preview/$resourceId'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/pricing'
    | '/reset-password'
    | '/verify-email'
    | '/_authenticated/admin'
    | '/_authenticated/bookmarks'
    | '/_authenticated/dashboard'
    | '/_authenticated/library'
    | '/_authenticated/my-uploads'
    | '/_authenticated/notifications'
    | '/_authenticated/premium'
    | '/_authenticated/profile'
    | '/_authenticated/settings'
    | '/_authenticated/upload'
    | '/_authenticated/admin/approvals'
    | '/_authenticated/admin/categories'
    | '/_authenticated/admin/users'
    | '/_authenticated/preview/$resourceId'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PricingRoute: typeof PricingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/upload': {
      id: '/_authenticated/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof AuthenticatedUploadRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/premium': {
      id: '/_authenticated/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof AuthenticatedPremiumRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-uploads': {
      id: '/_authenticated/my-uploads'
      path: '/my-uploads'
      fullPath: '/my-uploads'
      preLoaderRoute: typeof AuthenticatedMyUploadsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/library': {
      id: '/_authenticated/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AuthenticatedLibraryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bookmarks': {
      id: '/_authenticated/bookmarks'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof AuthenticatedBookmarksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/preview/$resourceId': {
      id: '/_authenticated/preview/$resourceId'
      path: '/preview/$resourceId'
      fullPath: '/preview/$resourceId'
      preLoaderRoute: typeof AuthenticatedPreviewResourceIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/categories': {
      id: '/_authenticated/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AuthenticatedAdminCategoriesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/approvals': {
      id: '/_authenticated/admin/approvals'
      path: '/approvals'
      fullPath: '/admin/approvals'
      preLoaderRoute: typeof AuthenticatedAdminApprovalsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminApprovalsRoute: typeof AuthenticatedAdminApprovalsRoute
  AuthenticatedAdminCategoriesRoute: typeof AuthenticatedAdminCategoriesRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminApprovalsRoute: AuthenticatedAdminApprovalsRoute,
  AuthenticatedAdminCategoriesRoute: AuthenticatedAdminCategoriesRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedBookmarksRoute: typeof AuthenticatedBookmarksRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedLibraryRoute: typeof AuthenticatedLibraryRoute
  AuthenticatedMyUploadsRoute: typeof AuthenticatedMyUploadsRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedPremiumRoute: typeof AuthenticatedPremiumRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedUploadRoute: typeof AuthenticatedUploadRoute
  AuthenticatedPreviewResourceIdRoute: typeof AuthenticatedPreviewResourceIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedBookmarksRoute: AuthenticatedBookmarksRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedLibraryRoute: AuthenticatedLibraryRoute,
  AuthenticatedMyUploadsRoute: AuthenticatedMyUploadsRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedPremiumRoute: AuthenticatedPremiumRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedUploadRoute: AuthenticatedUploadRoute,
  AuthenticatedPreviewResourceIdRoute: AuthenticatedPreviewResourceIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PricingRoute: PricingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  VerifyEmailRoute: VerifyEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
